- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker container
      docker_container:
        name: banking_project
        image: ranjitasm/banking-project:1.0
        state: started
        ports:
          - "8084:8081"
