- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Updating apt 
      command: sudo apt-get update
      
    - name: Install Docker
        name: sudp apt-get install -y docker.io

    - name: Start Docker service
        name:sudo systemctl start docker
        
    - name: Deploy Docker container
    command: docker run -itd -p 8084:8081 ranjitasm/banking-project:1.0
    
